---
title: "Vignette Lynx"
author: "Pierre Gloaguen"
date: "29 janvier 2020"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE, message = FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

# Lynx and hares data set

```{r hares_lynx, echo = F}
hares_lynx_data <- tribble(~Year,	~Hares,	~Lynx,
                           1900,	30,	4,
                           1901,	47.2,	6.1,
                           1902,	70.2,	9.8,
                           1903,	77.4,	35.2,
                           1904,	36.3,	59.4,
                           1905,	20.6,	41.7,
                           1906,	18.1,	19,
                           1907,	21.4,	13,
                           1908,	22,	8.3,
                           1909,	25.4,	9.1,
                           1910,	27.1,	7.4,
                           1911,	40.3,	8,
                           1912,	57,	12.3,
                           1913,	76.6,	19.5,
                           1914,	52.3,	45.7,
                           1915,	19.5,	51.1,
                           1916,	11.2,	29.7,
                           1917,	7.6,	15.8,
                           1918,	14.6,	9.7,
                           1919,	16.2,	10.1,
                           1920,	24.7,	8.6)
```

```{r showing_data, echo = F}
knitr::kable(hares_lynx_data)
```


## Setting model

You can also embed plots, for example:

```{r pressure, echo=FALSE}
a1 <- c(0.695617134, 0.001147425, 0.030333635) # Prey parameters
a2 <- c(0.630905980, 0.021756719, 0.001352425) # Predator parameters
Gamma <- matrix(c(0.22, 0, 0, 0.2), nrow = 2) # Diffusion parameters
mu0 <- c(30, 4) # Mean of the inital distribution
Sigma0 <- diag(1, 2) # Variance of the initial distribution

# Observation process parameters

Sigma_obs <- matrix(c(0.01, 0.00, 0.00, 0.01), ncol = 2) # Observation noise
q_values <- c(1, 1) # Known q values
initial_param <- list(a1 = a1, a2 = a2, mu0 = mu0,
                        sigma0 = Sigma0, RWC = diag(0.005, 2), 
                        qs = q_values, cov = Sigma_obs,
                        wD = 1, wO = 1,
                        gam = Gamma)
nf <- 20
observations <- hares_lynx_data[1:nf, ] %>% 
  select(Hares, Lynx) %>% 
  as.matrix()
observation_times <- pull(hares_lynx_data, Year)[1:nf]
library(LotkaVoltR)
set.seed(333)
particle_filter <- PF_create(initial_param, t(observations),
                             observation_times, 200,
                             n_euler_skel = 100)
smoothing_exp <- particle_filter$runSmoothing()
```

```{r}
particles <- particle_filter$get_particles()
weights <- particle_filter$get_weights()
sel_inds <- particle_filter$get_indexes() + 1
genealogy <- matrix(NA, nrow = nrow(weights), ncol = ncol(weights))
for(year in 1:ncol(genealogy)){
  tmp_gen <- genealogy[sel_inds[, year], ]
  tmp_gen[,year] <- sel_inds[, year]
  genealogy <- tmp_gen
}

smoothing_traj <- array(NA, dim = dim(particles))
for(i in 1:ncol(genealogy)){
  smoothing_traj[,, i] <- particles[genealogy[, i],, i]
}

save(smoothing_exp, particles, weights, sel_inds, smoothing_traj, genealogy,
     file = "smoothing_from_th0.RData")
```


```{r}
online_est <- smoothing_exp %>% 
  as.data.frame() %>% 
  rename(Hares = V1, Lynx = V2) %>%
  mutate(weight = 1,
         id = 999,
         Year = 1900:1920,
         type = "Smooth. Exp.")
map_dfr(1:21, 
        function(i){
          smoothing_traj[,, i] %>% 
            as.data.frame() %>% 
            rename(Hares = V1, Lynx = V2) %>%
            mutate(weight = weights[, 21],
                   id = 1:100,
                   Year = 1899 + i)
        }) %>% 
  mutate(type = "particles") %>% 
  bind_rows(mutate(hares_lynx_data, type = "observations",
                   weight = 1, id = 0)) %>% 
  bind_rows(online_est) %>% 
  ggplot(aes(x = Hares, y = Lynx, col = type, group = id)) +
  geom_path(aes())
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
