// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// runLV_PF
void runLV_PF(arma::mat obs_, Rcpp::NumericVector obsTimes_, Rcpp::List myParams, unsigned int n_part, unsigned int n_dens_samp);
RcppExport SEXP _LotkaVoltR_runLV_PF(SEXP obs_SEXP, SEXP obsTimes_SEXP, SEXP myParamsSEXP, SEXP n_partSEXP, SEXP n_dens_sampSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type obs_(obs_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type obsTimes_(obsTimes_SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type myParams(myParamsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_part(n_partSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_dens_samp(n_dens_sampSEXP);
    runLV_PF(obs_, obsTimes_, myParams, n_part, n_dens_samp);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_LV_Module();
RcppExport SEXP _rcpp_module_boot_LVPOD_Module();
RcppExport SEXP _rcpp_module_boot_PF_Module();
RcppExport SEXP _rcpp_module_boot_ProposalLVModel_Module();

static const R_CallMethodDef CallEntries[] = {
    {"_LotkaVoltR_runLV_PF", (DL_FUNC) &_LotkaVoltR_runLV_PF, 5},
    {"_rcpp_module_boot_LV_Module", (DL_FUNC) &_rcpp_module_boot_LV_Module, 0},
    {"_rcpp_module_boot_LVPOD_Module", (DL_FUNC) &_rcpp_module_boot_LVPOD_Module, 0},
    {"_rcpp_module_boot_PF_Module", (DL_FUNC) &_rcpp_module_boot_PF_Module, 0},
    {"_rcpp_module_boot_ProposalLVModel_Module", (DL_FUNC) &_rcpp_module_boot_ProposalLVModel_Module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_LotkaVoltR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
