# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Class SDE model
#' @name LV_simple
#' @description bivariate SDE LV model
#' @export LVModel
NULL

#' @title Class of partially diffusion process ruled by a LV model
#' @name LVPOD
#' @description POD with the bivariate SDE LV model
#' and the observation model Y_t = X_t * exp(N(0, Sigma_obs)) 
#' @export LVPOD
NULL

#' @title Class ParticleFilter
#' @name LV_PF
#' @description Class to run a particle filter
#' @export LVParticleFilter
NULL

#' @title ProposalModel for LVPOD
#' @name ProposalLVModel
#' @description Proposoal model with optimal filter
#' POD with the bivariate SDE LV model
#' and the observation model Y_t = X_t * exp(N(0, Sigma_obs))
#' @export ProposalLVModel
NULL

#'@title Run a Particle Filter on a POD based on a continuous LV model
#'@name get_E_step
#'@param a1 a2 Prey predatorsparameters
#'@param obs matrix of observations
#'@param obsTimes_ vector of ordered obs times
#'@param cov qs RWC some parameters
#'@param n_part number of particles
#'@param n_dens_samp number of sampling for density
#'@return a list with particles and weights
#'@export
get_E_step <- function(obs_, obsTimes_, myParams, testedParams, n_part, n_dens_samp) {
    .Call('_LotkaVoltR_get_E_step', PACKAGE = 'LotkaVoltR', obs_, obsTimes_, myParams, testedParams, n_part, n_dens_samp)
}

